### ISSUE TITLE
Assertion Error in Query 26 test

### ISSUE THREAD

**Issue by Wajihulhassan** [IntelLabs/HPAT.jl#13]
Hi, I am getting following error when I run query 26 test.

`julia --depwarn=no /home/wajih/.julia/v0.4/HPAT/test/q26_test.jl 
     Testing Query 26[small]
ERROR: LoadError: AssertionError: nodes[i - 1].head == :(=) && nodes[i - 1].args[1] == set_in
 in translate_join at /home/wajih/.julia/v0.4/HPAT/src/domain-pass.jl:363
 in translate_table_oprs at /home/wajih/.julia/v0.4/HPAT/src/domain-pass.jl:166
 in from_toplevel_body at /home/wajih/.julia/v0.4/HPAT/src/domain-pass.jl:115
 in from_root at /home/wajih/.julia/v0.4/HPAT/src/domain-pass.jl:83
 in runDomainPass at /home/wajih/.julia/v0.4/HPAT/src/HPAT.jl:134
 in processFuncCall at /home/wajih/.julia/v0.4/CompilerTools/src/OptFramework.jl:442
 in q26 at /home/wajih/.julia/v0.4/CompilerTools/src/OptFramework.jl:557
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/wajih/.julia/v0.4/HPAT/test/q26_test.jl, in expression starting on line 87` 

I am using Julia 0.4.6 and Ubuntu 16.04.

**Comment by ehsantn** [comment]
I am moving everything to 0.5 and seems like supporting 0.4 simultaneously is too much trouble since the AST has change substantially. I suggest you move to 0.5 too. There is still some issue with aggregate that will be resolved soon I think.

**Comment by ehsantn** [comment]
This will take a while since pushing filter up optimization has to be rewritten. We cannot rely on Symbol names in 0.5.

**Comment by Wajihulhassan** [comment]
Definitely, this will take a while if cannot rely on Symbol names. I still need to go over the 0.5 release changes to identify what exact parts to be changed for table pass.

**Comment by Wajihulhassan** [comment]
We should tag HPAT repo for 0.4 if we want to fall back to 0.4(for julia 0.4 users)
