### ISSUE TITLE
Error trying to execute 1D Sum example

### ISSUE THREAD

**Issue by rafaelcarv** [IntelLabs/HPAT.jl#16]
Hello, I am trying to execute the 1D Sum example, I updated all my environment, and i am using Julia 0.5

Did the checkout from all the intel packages (ParalellAccelerator, CompilerTools and HPAT). However, i am not able to execute the example.

I am using Ubuntu 16.04.

I am attaching a file with the error output.

[out.txt](https://github.com/IntelLabs/HPAT.jl/files/488323/out.txt)

**Comment by ehsantn** [comment]
Seems like your HDF5 is not installed properly. You could try (Ubuntu):
```
sudo apt-get install -qq libmpich2-dev mpich2 hdf5-tools libhdf5-mpich2-dev
```
or build from source:
https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/release_docs/INSTALL_parallel
You might want to add the include directory to the system environment:
```
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/hdf5/include
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/local/hdf5/include
```

**Comment by Wajihulhassan** [comment]
@rafaelcarv For Ubuntu, in addition to steps mentioned on HPAT's README, run commands from this wiki:
https://github.com/IntelLabs/HPAT.jl/wiki/HPAT-Installation-on-Ubuntu-16.04

**Comment by rafaelcarv** [comment]
Hello,

After following these instructions (Ehsan instruction, plus the wiki instruction), the HDF5 error is not occurring anymore, however I am getting the following error:


file= /tmp/1D_large.hdf5
OptFramework failed to optimize function ##calc1Dsum#271 in optimization pass HPAT.runDistributedPass with error UndefVarError(:computeDependenciesAST)
ERROR: LoadError: error compiling ##calc1Dsum#271: unsupported or misplaced expression "alloc" in function ##calc1Dsum#271
 in calc1Dsum(::String) at /home/rafael/.julia/v0.5/CompilerTools/src/OptFramework.jl:577
 in main() at /home/rafael/.julia/v0.5/HPAT/examples/1D_sum.jl:62
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/rafael/.julia/v0.5/HPAT/examples/1D_sum.jl, in expression starting on line 75

**Comment by Wajihulhassan** [comment]
@rafaelcarv . I fired up a new VM of Ubuntu 16.04. I built and installed release-0.5 Julia from the github and followed the instructions on README and wiki. And successfully ran HPAT tests. I did not get your error.
```
wajih@wajih:~/.julia/v0.5/HPAT/examples (master)*$ julia --depwarn=no 1D_sum.jl 
WARNING: Method definition (::Type{ParallelAccelerator.ParallelIR.PIRParForAst})(Any, Any, Any, Any, Any, Any, Any, Any, Any, Any, Any) in module ParallelIR at /home/wajih/.julia/v0.5/ParallelAccelerator/src/parallel-ir.jl:359 overwritten at /home/wajih/.julia/v0.5/ParallelAccelerator/src/parallel-ir.jl:363.
file= /home/wajih/.julia/v0.5/HPAT/src/../input_data/1D_large.hdf5
Distributed-memory MPI mode.
OpenMP is not used.
Main will be generated in file main1.cc
Data for main will be in file main1.data
Script to compile is in main1.sh
SELFPRIMED 35.689845293
Main will be generated in file main2.cc
Data for main will be in file main2.data
Script to compile is in main2.sh
result = 499762.93314082833
SELFTIMED 0.003996779
wajih@wajih:~/.julia/v0.5/HPAT/examples (master)*$ 
```
Just  make sure all the packages HPAT, ParallelAccelerator, and CompilerTools are checkout to master branch. Then generate dataset with the script in the HPAT repo `generate_data/generate_1D_array.jl` and run the example. Try to follow the steps again and let me know if you see the error again.

**Comment by rafaelcarv** [comment]
Thanks,

I just reinstalled everything in a new VM and it worked.
