### ISSUE TITLE
Output Messages

### ISSUE THREAD

**Issue by rafaelcarv** [IntelLabs/HPAT.jl#18]
Hello, 

There's a way to stop showing the **"Main will be generated in file main1.cc"** messages?
I want to save the output of my application in a file, and there's a lot of these messages in its output.

Thanks,

Rafael

**Comment by ehsantn** [comment]
You can comment out lines 2651-3 in `~/.julia/v0.5/ParallelAccelerator/src/cgen.jl`. Maybe we should remove these messages altogether. We also need some documentation on standalone no-Julia mode.

**Comment by rafaelcarv** [comment]
I think that would be interesting to use some kind of Log, instead of prints. So if there are places that should send information to the developers, they log in a file, or show on screen. And separate the in types of information levels: info, warn and error. 

So, if the user want to have no "info" prints on screen, just change a file to get only the error messages. Or send the log to a file, to check the execution flow later.

Because, there are other output messages as well:

Distributed-memory MPI mode.
OpenMP is not used.

I don't know if exists an equivalent Log4j for Julia, but i think would be a nice thing to do. So you would still have the informations messages to track.
