### ISSUE TITLE
Can Intel DAAL / Intel MKL be Open Sourced?

### ISSUE THREAD

**Issue by sirinath** [IntelLabs/HPAT.jl#2]
It would be good if HPAT dependencies and other numeric and parallel computing libraries are FOSSed under a permissive license.

**Comment by ehsantn** [comment]
I don't know the plans for open-source release of those libraries. However, HPAT should be able to work with any back-end since it can generate input/output transformations. We plan to support alternative open-source libraries.

**Comment by sirinath** [comment]
What libraries do you plan to support and are there benchmarks for these libraries?

**Comment by ehsantn** [comment]
We are still looking for options. There aren't many distributed-memory machine learning libraries. Do you have any suggestions?

**Comment by sirinath** [comment]
My suggestion would be to get the above 2 open sourced. 

Also see:

 - http://www.dmtk.io/
 - http://petuum.github.io/
 - http://dmlc.ml/
 - http://autumnai.com/
 - https://www.tensorflow.org/
 - http://caffe.berkeleyvision.org/
 - http://libelemental.org/

**Comment by sirinath** [comment]
http://mlpack.org/

**Comment by ehsantn** [comment]
Thank you for the suggestions. We will look into supporting more back-end libraries. Contributions are also welcome.

**Comment by sirinath** [comment]
http://arrayfire.com/
